In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
#Matrix Addition
import numpy as np
a=np.array([[1,2,3],[4,7,3],[2,6,3]])
b=np.array([[2,4,8],[3,3,7],[4,7,5]])
mat_sum=a+b
print ("Matrix Multiplication is :",mat_sum)

Matrix Multiplication is : [[ 3  6 11]
 [ 7 10 10]
 [ 6 13  8]]


In [3]:
#Matrix Subtraction
import numpy as np
a=np.array([[1,2,3],[4,7,3],[2,6,3]])
b=np.array([[2,4,8],[3,3,7],[4,7,5]])
mat_sub=a-b
print ("Matrix Subtraction is :",mat_sub)

Matrix Subtraction is : [[-1 -2 -5]
 [ 1  4 -4]
 [-2 -1 -2]]


In [4]:
#Matrix Multiply
import numpy as np
a=np.array([[1,2,3],[4,7,3],[2,6,3]])
b=np.array([[2,4,8],[3,3,7],[4,7,5]])
mat_mul=a*b
print ("Matrix Multiplication is :",mat_mul)

Matrix Multiplication is : [[ 2  8 24]
 [12 21 21]
 [ 8 42 15]]
